import { Button, Center, Heading } from "@chakra-ui/react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <Heading>Hello Chakra With nextjs</Heading>
        <Button colorScheme="teal">Chakra Button</Button>
      </Center>
    </>
  );
};

export default Home;
